#if PCL
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using WampSharp.V2.Rpc;
using TaskExtensions = WampSharp.Core.Utilities.TaskExtensions;

namespace WampSharp.CodeGeneration
{
    public class CalleeProxyCodeGenerator
    {
        private readonly string mNamespaceName;

        private readonly string mClassDeclarationTemplate =
@"using System;
using System.Reflection;
using System.Threading.Tasks;
using WampSharp.V2;
using WampSharp.V2.CalleeProxy;
using WampSharp.V2.Client;

namespace {$namespace}
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------
    public class {$proxyName}Proxy : CalleeProxyBase, {$implementedInterface}
    {
{$fields}

        public {$proxyName}Proxy
                (IWampRpcOperationCatalogProxy rpcCatalog,
                 IWampClientConnectionMonitor monitor, 
                 ICalleeProxyInterceptor interceptor)
            : base(rpcCatalog, monitor, interceptor)
        {
        }
{$implementedMethods}
    }
}";
        public CalleeProxyCodeGenerator(string namespaceName)
        {
            mNamespaceName = namespaceName;
        }

        public string GenerateCode(Type interfaceType)
        {
            ProxyMethodWriter writer = new ProxyMethodWriter();

            List<string> methods = new List<string>();
            List<string> fields = new List<string>();

            int methodIndex = 0;

            foreach (MethodInfo method in interfaceType.GetPublicInstanceMethods())
            {
                string methodCode = writer.WriteMethod(methodIndex, method);
                string methodField = writer.WriteField(methodIndex, method);
                methods.Add(methodCode);
                fields.Add(methodField);
                methodIndex++;
            }

            string joinedMethods = JoinLines(methods);
            string joinedFields = JoinLines(fields);

            IDictionary<string, string> dictionary = 
                new Dictionary<string, string>();

            dictionary["namespace"] = mNamespaceName;
            dictionary["fields"] = joinedFields;
            dictionary["implementedMethods"] = joinedMethods;
            dictionary["implementedInterface"] = FormatTypeExtensions.FormatType(interfaceType);
            dictionary["proxyName"] = GetInterfaceName(interfaceType);

            string processed = TemplateHelper.ProcessTemplate(mClassDeclarationTemplate, dictionary);

            return processed;
        }

        private static string JoinLines(List<string> lines)
        {
            string joinedLines =
                string.Join(Environment.NewLine, lines);

            joinedLines =
                string.Join(Environment.NewLine,
                            joinedLines.Split(new[] {Environment.NewLine}, StringSplitOptions.None)
                                         .Select(x => "        " + x));
            return joinedLines;
        }

        private string GetInterfaceName(Type interfaceType)
        {
            string result = interfaceType.Name;

            if (result.StartsWith("I"))
            {
                return result.Substring(1);
            }
            else
            {
                return result;
            }
        }
    }

    public interface IProxyMethodWriter
    {
        string WriteMethod(int methodIndex, MethodInfo method);
    }

    class ProxyMethodWriter : IProxyMethodWriter
    {
        private string mMethodTemplate =
@"
public {$returnType} {$methodName}({$parametersDeclaration})
{
    {$return}{$invokeMethod}{$genericType}({$parameterList});
}";

        public string WriteMethod(int methodIndex, MethodInfo method)
        {
            string methodField = "mMethod" + methodIndex;
            
            IDictionary<string, string> dictionary =
                new Dictionary<string, string>();

            ParameterInfo[] parameters = method.GetParameters();

            dictionary["methodName"] = method.Name;
            dictionary["parameterList"] =
                string.Join(", ",
                            new[] {methodField}.Concat(parameters.Select(x => x.Name)));

            dictionary["returnType"] = FormatTypeExtensions.FormatType(method.ReturnType);

            string invokeMethod;

            if (method.GetCustomAttribute<WampProgressiveResultProcedureAttribute>() != null)
            {
                invokeMethod = "InvokeProgressiveAsync";

                dictionary["parameterList"] =
                    string.Join(", ",
                                new[] {methodField}.Concat
                                    (new[] {parameters.Last()}.Concat(parameters.Take(parameters.Length - 1))
                                                              .Select(x => x.Name)));
            }
            else if (typeof (Task).IsAssignableFrom(method.ReturnType))
            {
                invokeMethod = "InvokeAsync";
            }
            else
            {
                invokeMethod = "InvokeSync";
            }

            Type returnType = TaskExtensions.UnwrapReturnType(method.ReturnType);

            if (method.ReturnType != typeof(void))
            {
                dictionary["return"] = "return ";
                dictionary["genericType"] = GetGenericType(returnType);
            }
            else
            {
                dictionary["return"] = string.Empty;
                dictionary["genericType"] = string.Empty;
            }

            if (method.ReturnType == typeof (Task))
            {
                dictionary["genericType"] = string.Empty;                
            }

            if (!method.HasMultivaluedResult())
            {
                invokeMethod = "Single" + invokeMethod;
            }
            else
            {
                invokeMethod = "Multi" + invokeMethod;
                dictionary["genericType"] = GetGenericType(returnType.GetElementType());
            }

            dictionary["invokeMethod"] = invokeMethod;

            dictionary["parametersDeclaration"] =
                string.Join(", ",
                            parameters.Select
                                (x => FormatTypeExtensions.FormatType(x.ParameterType) + " " + x.Name));

            return TemplateHelper.ProcessTemplate(mMethodTemplate, dictionary);
        }

        private static string GetGenericType(Type returnType)
        {
            return string.Format("<{0}>", FormatTypeExtensions.FormatType(returnType));
        }

        private string mFieldTemplate =
            @"private static readonly MethodInfo mMethod{$methodIndex} = GetMethodInfo(({$interfaceType} instance) => instance.{$methodName}({$defaults}));";

        public string WriteField(int methodIndex, MethodInfo method)
        {
            Dictionary<string, string> dictionary = new Dictionary<string, string>();

            Type type = method.DeclaringType;

            dictionary["methodIndex"] = methodIndex.ToString();
            dictionary["interfaceType"] = FormatTypeExtensions.FormatType(type);
            dictionary["methodName"] = method.Name;
            dictionary["defaults"] =
                string.Join(", ",
                            method.GetParameters()
                                  .Select(x => string.Format("default({0})",
                                                             FormatTypeExtensions.FormatType(x.ParameterType))));

            return TemplateHelper.ProcessTemplate(mFieldTemplate, dictionary);
        }
    }
}
#endif