name: GitHub packages NuGet generation

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest
    name: Update NuGet 
    steps:

      - name: Checkout repository
        uses: actions/checkout@master

      - name: Build solution and generate NuGet package
        run: |  
          cd src\netstandard\
          dotnet pack -c Release -o out --version-suffix develop

      - name: Install NuGet client
        uses: warrenbuckley/Setup-Nuget@v1

      - name: Add private GitHub registry to NuGet
        run: nuget sources add -name "GPR" -Source https://nuget.pkg.github.com/Code-Sharp/index.json -Username Code-Sharp -Password ${{ secrets.GITHUB_TOKEN }}

      - name: Push generated package to GitHub registry
        run: nuget push .\**\out\*.nupkg -Source "GPR" -SkipDuplicate